#!/bin/sh
# 

. "${PM_FUNCTIONS}"

case "$1" in
	hibernate|suspend)
		/opt/socketcan/can-shutdown.sh &> /dev/null
		;;
	thaw|resume)
		/opt/socketcan/can-setup.sh &> /dev/null
		;;
	*) exit $NA
		;;
esac
